name: Auto Merge
on:
  pull_request:
    branches: [main] # run on pull requests to main branch
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # setup repository in runner
      - name: Setup Node.js # setup Node.js un runner
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile # install dependencies
      - run: yarn build # build project
      - run: yarn test:unit # run tests
  mergepal-merge: # merge when build and testing is successful
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - uses: actions/checkout@v2
      - uses: maxkomarychev/merge-pal-action@v0.5.1
        with:
          token: ${{secrets.PERSONAL_TOKEN}}
